import { getDocuments } from "@/lib/docs";
import { Inter } from "next/font/google";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DocuCraft - A simple docucraft portal",
  description: "Generated by Hasan U Khan",
};

export default function RootLayout({ children }) {

  const allDocuments = getDocuments();
  console.log(allDocuments);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
